complete -c proj -n '__fish_is_first_token' -a '(proj __complete commands 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from open; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from open; and test (count (commandline -opc)) -eq 3' -a '(proj __complete editors 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from open; and test (count (commandline -opc)) -eq 3' -a '-r --root --wt'
complete -c proj -n '__fish_seen_subcommand_from pwd; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from pwd; and test (count (commandline -opc)) -eq 3' -a '--wt'
complete -c proj -n '__fish_seen_subcommand_from wt; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from status rm' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from set; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from set; and test (count (commandline -opc)) -eq 3' -a 'name owner created tracker editor workspace code_workspace'
complete -c proj -n '__fish_seen_subcommand_from get; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from get; and test (count (commandline -opc)) -eq 3' -a 'name owner created'
complete -c proj -n '__fish_seen_subcommand_from mv' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from fav' -a '(proj __complete projects 2>/dev/null)'
