complete -c proj -n '__fish_is_first_token' -a '(proj __complete commands 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from open; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from open; and test (count (commandline -opc)) -eq 3' -a '(proj __complete editors 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from status pwd rm' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from set; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from set; and test (count (commandline -opc)) -eq 3' -a 'name owner created tracker editor'
complete -c proj -n '__fish_seen_subcommand_from get; and test (count (commandline -opc)) -eq 2' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from get; and test (count (commandline -opc)) -eq 3' -a 'name owner created'
complete -c proj -n '__fish_seen_subcommand_from mv' -a '(proj __complete projects 2>/dev/null)'
complete -c proj -n '__fish_seen_subcommand_from fav' -a '(proj __complete projects 2>/dev/null)'
